### ISSUE TITLE
Player inventory empty when opening GUI

### ISSUE THREAD

**Issue by ghost** [Patbox/sgui#10]
Maybe I'm doing something very stupid / making an obvious mistake, but when I open the inventory using the following code
```java
var gui = new SimpleGui(ScreenHandlerType.GENERIC_9X3, (ServerPlayerEntity) player, true);
gui.open();
```
The player's inventory is fully empty. Notice how the items in my hotbar are gone as well. They do return after I close the inventory again though.

![GIF showing the problem](https://user-images.githubusercontent.com/78665317/147348624-8a5b07fb-c4f3-41dc-a0ca-29c4a8613bc4.gif)

**Comment by Patbox** [comment]
Thats intended, as you set includePlayerInventory (last argument) to true. You want it set to false if you want to keep player inventory visible

**Comment by ghost** [comment]
Oh my god I just realized that I feel so stupid now lol. Thanks for the quick reply!

I would suggest renaming that argument though, because it seemed logical to me that setting it to `true` would actually show the inventory slots (it is documented however so its actually fine).
