### ISSUE TITLE
[Bug] `includePlayerInventorySlots` not working

### ISSUE THREAD

**Issue by alex3236** [Patbox/sgui#14]
### Env
Minecraft 1.18.2, Java 17, Windows 11 Professional

### Problem
Player inventory would displayed even if `includePlayerInventorySlots` is `false`.

![image](https://user-images.githubusercontent.com/45303195/163903077-2229bd9d-5467-4508-9288-18a9584a1706.png)
![image](https://user-images.githubusercontent.com/45303195/163903146-01fe5ff3-c87d-4b8c-a68b-d080ffa242f1.png)

**Comment by Patbox** [comment]
Did you have any items? false leaves content of vanilla inventory, true makes these slots part of gui

**Comment by alex3236** [comment]
> Did you have any items? false leaves content of vanilla inventory, true makes these slots part of gui

Sorry, I misunderstood the meaning of this option.
