### ISSUE TITLE
move to architectury?

### ISSUE THREAD

**Issue by anar4732** [Patbox/sgui#35]

**Comment by Stikulzon** [comment]
why

**Comment by Patbox** [comment]
I don't use forge, so I don't see much value in doing so, just more dev time required

**Comment by anar4732** [comment]
Makes sense. What do you think about if i pull request it？

**Comment by Patbox** [comment]
It still requires future maintenance that I don't really want to do, feel free to create a fork that runs on forge through

**Comment by anar4732** [comment]
I don't think maintenance will make much difference since this uses mostly vanilla things

**Comment by Patbox** [comment]
There was a fork some time ago that ported this to forge and from what I've heard from dev some of forge's patches broke things with it. I also would need to actually test it and it would make me dependent on forge's release cycle (which is slower than fabric's, as I generally start porting my mods/libraries on prereleases with target of releasing before Mojang's official full release)

**Comment by anar4732** [comment]
Okay thank you for tge fast response

**Comment by anar4732** [comment]
PS: I did this [anar4732/sgui](https://github.com/anar4732/sgui) I didn't notice anything breaking or exploding.
