### ISSUE TITLE
opening the gui

### ISSUE THREAD

**Issue by lukehodges** [Patbox/sgui#8]
ik this is a nooby question but ive followed along with the test mod but idk how i would spawn a gui. I have tried `MinecraftClient.getInstance().setScreen` and `playerEntity.openHandledScreen` but neither work. any ideas?

**Comment by Patbox** [comment]
Just call .open() on gui object. sgui is also server side only, so you shouln't touch client classes with it

**Comment by lukehodges** [comment]
tysm ill try that now

**Comment by lukehodges** [comment]
@Patbox solved!
